language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "revaturelabs"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean sonar:sonar org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package 