spring:
  application:
    name: category-service

  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    username: sa
    password: password

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

server:
  port: 10001

---
spring:
  profiles:
    active: dev
server:
  port: 80

