spring:
  application:
    name: category-service

  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: h2
    url: jdbc:h2:mem:caliber;Mode=PostgreSQL
    username: sa
    password: password

server:
  port: 10000
  error:
    include-stacktrace: never
---
spring:
  profiles:
    active: local
  cloud:
    kubernetes:
      secrets:
        enabled: false
      config:
        enabled: false
      reload:
        enabled: false
  security:
    oauth2:

      resourceserver:
        jwt:
          issuer-uri: https://localhost:9443/oauth2/token
          jwk-set-uri: https://localhost:9443/oauth2/jwks

---
spring:
  profiles:
    active: kubernetes

  management:
    endpoint:
      restart:
        enabled: true
      health:
        enabled: true
      info:
        enabled: true
  server:
    port: 80

