server:
  port: 8013

spring:
  application:
    name: category-service
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
    
eureka:
  client:
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

#feign:
#  hystrix:
#    enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream