spring:
  application:
    name: category-service

  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    username: sa
    password: password

server:
  port: 10001

---
spring:
  profiles:
    active: local
  cloud:
    kubernetes:
      secrets:
        enabled: false
      config:
        enabled: false
      reload:
        enabled: false
---
spring:
  profiles:
    active: kubernetes

  management:
    endpoint:
      restart:
        enabled: true
      health:
        enabled: true
      info:
        enabled: true
  server:
    port: 80

